languageCode = 'en-us'
title = 'NullSheen Shadowrun Tools'
theme = 'q'
Paginate = 10
DefaultContentLanguage = "en"
enableRobotsTXT = true
show_reading_time = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Matrix Gen (3rd)"
  weight = 1
  url = "https://matrix.nullsheen.com"

[[menu.main]]
  name = "Matrix Builder (2nd)"
  weight = 2
  url = "https://matrix2.nullsheen.com"

[[menu.main]]
  name = "Init Tracker"
  weight = 3
  url = "https://initiative-tracker.nullsheen.com/"

[[menu.main]]
  name = "Tools"
  weight = 4
  url = "https://www.nullsheen.com/software/"

[[menu.main]]
  name = "Contact"
  weight = 5
  url = "https://www.nullsheen.com/contact/"

[[menu.main]]
  name = "About Me"
  weight = 6
  url = "https://www.nullsheen.com/about-me/"

[[menu.main]]
  name = "Shadowrun Books"
  weight = 7
  url = "https://www.nullsheen.com/shadowrun-books/" 
